### ISSUE TITLE
Credits.getReleases is not working = No such function error 

### ISSUE THREAD

**Issue by Deery5000** [cavestri/themoviedb-javascript-library#12]
This method is not working

  getReleases: function (options, success, error) {
        'use strict';

        theMovieDb.common.validateRequired(arguments, 3, options, ["id"]);

        theMovieDb.common.validateCallbacks([success, error]);

        theMovieDb.common.client(
            {
                url: "movie/" + options.id + "/releases" + theMovieDb.common.generateQuery(options)
            },
            success,
            error
        );
    },

**Comment by cavestri** [comment]
Thanks for the advice, I will fix it in the next 24 hours.

**Comment by cavestri** [comment]
I have fixed the wiki, the problem was that getReleases is a method of movies not of credits:

https://github.com/cavestri/themoviedb-javascript-library/wiki/Movies

```javascript
theMovieDb.movies.getReleases({"id": 76203}, successCB, errorCB)
```
Sry for that.
