### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by vanzylv** [cavestri/themoviedb-javascript-library#13]
Firstly thanks for a great library.

Making request to themoviedb seem to have cross-domain issues now,I'm pretty sure this worked without a jsonp callback.Looking at the example apps on here I get the same issue.

XMLHttpRequest cannot load http://api.themoviedb.org/3/discover/movie?api_key=3d197569c7f13f60d61a7d61d5c83427&year=2009. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://codenatic.com' is therefore not allowed access.

Am I missing something?

Thanks

**Comment by arjunu** [comment]
Even with jsonp it's not working. If we provide callback parameter, the response isn't being wrapped in it.

**Comment by cavestri** [comment]
Hi, sorry for the delay. Right now I can't reproduce the error, could you post some example code or a link where I can see the issue? 

The "Guess The Movie" game example works for me.

Thanks!

**Comment by vanzylv** [comment]
No problem,apologies,this did not work for whatever reason from work but it works from home,they might have some proxy restrictions or something.Thanks for the reply and thanks for the work you've done on the library.
