### ISSUE TITLE
theMovieDb.credits

### ISSUE THREAD

**Issue by mc2nzo137** [cavestri/themoviedb-javascript-library#14]
Hi,
in the theMovieDb.credits method, the url is wrong:
url: "credit/" + options.id + theMovieDb.common.generateQuery(options)

this work fine:
url: "movie/" + options.id + "/credits" + theMovieDb.common.generateQuery(options)

Thanks for the project!

**Comment by cavestri** [comment]
Hi, we have 2 credits methods:

https://github.com/cavestri/themoviedb-javascript-library/wiki/Credits
theMovieDb.credits.getCredit(options, successCB, errorCB): _"This method allows you to get the detailed information about a particular credit record"_

https://github.com/cavestri/themoviedb-javascript-library/wiki/Movies
theMovieDb.movies.getCredits(options, successCB, errorCB): _"This method allows you to get the credits (casts and crew) of a movie"_

Greetings!
