### ISSUE TITLE
bower package

### ISSUE THREAD

**Issue by gwario** [cavestri/themoviedb-javascript-library#15]
It would be nice to have a bower package for your lib!

http://bower.io/docs/creating-packages/
i.e. on https://libraries.io/

**Comment by mbana** [comment]
I guess you can do something like below in you `bower.json`:

```sh
    "themoviedb-javascript-library": "git@github.com:cavestri/themoviedb-javascript-library.git"
```

**Comment by amilajack** [comment]
Why use bower when you can use npm?

**Comment by Fatih90** [comment]
@amilajack Why use github when you can use gitlab?

**Comment by amilajack** [comment]
npm is standard. gitlab isnt
