### ISSUE TITLE
more of a question: Will this library take into account for "Access-Control-Allow-Headers"? 

### ISSUE THREAD

**Issue by shreyashdholakia** [cavestri/themoviedb-javascript-library#20]
Planning to use it and my app will have basic authentication? So was wondering if it takes care of CORS ?

Thanks

**Comment by cavestri** [comment]
Hi, the library do not set the withCredentials options, so the defualt is false (as far I have read on: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials), you sould update the library for that.
