### ISSUE TITLE
version number

### ISSUE THREAD

**Issue by maruilian11** [cavestri/themoviedb-javascript-library#21]
hi, recently we want to your lib to https://cdnjs.com, can we regard current files as v1.0.0? we need a version number to put it to cdnjs. or if you have any idea? 
thank you very much!

https://github.com/cdnjs/cdnjs/issues/6491

**Comment by cavestri** [comment]
Hi, looks fine to me, we are not making any versioning... but it's a good time to start doing it.

**Comment by cavestri** [comment]
Done.

**Comment by maruilian11** [comment]
thanks a lot!
