### ISSUE TITLE
API Call returns as a an undefined type

### ISSUE THREAD

**Issue by kevinxia787** [cavestri/themoviedb-javascript-library#32]
Here is my call:

var dumcall = theMovieDb.discover.getMovies({"year": 2015, "with_genres": 28, "page":1}, successCB, errorCB);

Typing typeof(dumcall) in the chrome console returns "undefined"
Because of this, I am unable to access the elements of the JSON.

Any input will be appreciated

**Comment by cavestri** [comment]
Hi, that is ok.

All the methods in the library are asynchronous and you should wait the response using the callback methods, following your example:

Calling theMovieDb.discover.getMovies({"year": 2015, "with_genres": 28, "page":1}, successCB, errorCB); will return a response using successCB or errorCB methods, depending the server response.
