### ISSUE TITLE
npm package is outdated

### ISSUE THREAD

**Issue by itshaadi** [cavestri/themoviedb-javascript-library#33]
first of all, thank you so much this library is awesome :)
but i'm having some issue with CORS and based on #20 looks like you fixed the problem but npm package is outdated. also there is no function for multi search.

**Comment by cavestri** [comment]
Hi, I don't updated the library, in the bug that you refer maybe I not explain me correctly.

The TMDB server uses **"Access-Control-Allow-Origin: *"**, as far I know you could call it from everywhere without problems and the use of withCredentials is not allowed. 

If you need to use withCredentials you should updated your own library file, but i think that it will not work becasue the Access-Control-Allow-Origin.

About multi search, could you load another bug for that?

Thanks!

**Comment by itshaadi** [comment]
the problem is that TMDB main website is censored in iran. therefore i have to use anonymizer services.
anyway your library is fine, problem is anonymizer doesn't support CORS.
