### ISSUE TITLE
The resource you requested could not be found

### ISSUE THREAD

**Issue by DanCLee** [cavestri/themoviedb-javascript-library#34]
theMovieDb.credits.getCredit({"id" : Movie ID }, successCB, errorDB);

The Movie ID is provided by an object provided by theMovieDb.discover. 

{"status_code":34,"status_message":"The resource you requested could not be found."}

**Comment by cavestri** [comment]
Thanks for report it!

Is fixed now.

Greetings!

**Comment by DanCLee** [comment]
That's great to hear! Thank you for your hard work!
