### ISSUE TITLE
Not reading api_key in production build

### ISSUE THREAD

**Issue by davidgolden** [cavestri/themoviedb-javascript-library#37]
Everything was working fine in a development environment, but when I deployed it was seemingly not reading the api_key variable and throwing an error.  I was able to get it working by amending `query = "?api_key=4438a6...` rather than using the `theMovieDb.common.api_key` variable. Really no clue why this would happen but thought I should bring it to your attention. I'm using ReactJS.

**Comment by davidgolden** [comment]
Scratch that.. still not working :(

**Comment by cavestri** [comment]
Hi, sorry for the delay, I was on vacations. What error shows in browser console/network tab?

The GuessTheMovie example seems to be working fine: http://codenatic.com/demos/guessthemovie/

Greetings!

**Comment by cavestri** [comment]
No user feedback. If still happens, please re-open. Thanks!
