### ISSUE TITLE
How to change the language of api?

### ISSUE THREAD

**Issue by abrahaobittar** [cavestri/themoviedb-javascript-library#39]
how can i change the language of results? 
for exemple , i need to the return of getResultsById in pt-br, this is configurable?
thx

**Comment by cavestri** [comment]
Hi, currently you must sent the language code in the options parameter, e.g.:

`theMovieDb.discover.getMovies({'language': 'pt-BR'}, function(data){ console.log(data); }, function(data){ console.log(data); })`

this could be tedious, so i will add a config for that.

**Comment by abrahaobittar** [comment]
thx

**Comment by cavestri** [comment]
Added as configuration in common, check release 3.0.1
