### ISSUE TITLE
NPM package severely out of date

### ISSUE THREAD

**Issue by JonathanTroyer** [cavestri/themoviedb-javascript-library#40]
NPM lists this package at version 1.0.0, while 3.0.1 has been out for a few months now. Is there any way the NPM package can be updated?

**Comment by cavestri** [comment]
Hi, you say it for https://www.npmjs.com/package/themoviedb-javascript-library?

I don't know who added that package and don't know how to contact or publish a new version :(

**Comment by JonathanTroyer** [comment]
@cavestri thanks for responding so quickly! Yes, that's the package. I think you could try to [dispute the package](https://docs.npmjs.com/misc/disputes), as it links to your GitHub repo and hasn't been updated in years.

**Comment by cavestri** [comment]
oh ok, i will try that then. Thanks!

**Comment by cavestri** [comment]
Hi, I have updated the package with latest code. Thanks for the head up! :smiley: 

Greetings!
