### ISSUE TITLE
No export module

### ISSUE THREAD

**Issue by afzaalopera** [cavestri/themoviedb-javascript-library#41]
Can you explain please, why there is no exports.module = theMovieDb; in your themoviedb,js file.
I've tried both ways:
1) var theMovieDb = require('themoviedb-javascript-library')
and 
2) import theMovieDb from 'themoviedb-javascript-library';
Trying both these i get empty object
console.log(theMovieDb); // {} empty object

**Comment by afzaalopera** [comment]
UPDATE:
When i was using nom-package it was v1.0 and it was working fine, but after the update to that package, my whole application crashed. Investigating it i found out that you need to add the following to your themoviedb.js file
`if ((typeof module != 'undefined') && (module.exports)) {
	module.exports = theMovieDb;
}`
And this will resolve the issue.

**Comment by cavestri** [comment]
Oh, i see, thanks for finding the bug and contribute with the solution. :)
