### ISSUE TITLE
Remove rate methods require rate value

### ISSUE THREAD

**Issue by jeffreyspaan** [cavestri/themoviedb-javascript-library#44]
The following methods require a rating on removing a rating, which is not required according to the [TMDB documentation](https://developers.themoviedb.org/3/movies/delete-movie-rating).

`theMovieDb.movies.removeRate`
`theMovieDb.movies.removeRateGuest`
`theMovieDb.tv.removeRate`
`theMovieDb.tv.removeRateGuest`
`theMovieDb.tvEpisodes.removeRate`
`theMovieDb.tvEpisodes.removeRateGuest`

**Comment by cavestri** [comment]
Great review, thanks for it! :)
