### ISSUE TITLE
[Search] getMovie page option doesn't work.

### ISSUE THREAD

**Issue by delvedor** [cavestri/themoviedb-javascript-library#6]
Hi!
I'm using your library, compliments, a very nice work.

I've a problem in the page parameter in search.getMovie function, here's the code:
```javascript
theMovieDb.search.getMovie({
    "query": query,
    "page": 2,
    "include_adult": false
}, searchFilm, error);
```
The resulting json is always at the page:1 : 
```javascript
function searchFilm(data) {
    var ris = $.parseJSON(data);
    console.log('searchFilm', ris);
}
```
I've tried with the search.getKeywork in the same way, but it works without any problem.

**Comment by cavestri** [comment]
Hi, it seems to be a problem with the API server, I have created an issue in their forums:

http://www.themoviedb.org/talk/54ebecc7c3a3686d6d00098c

**Comment by delvedor** [comment]
Yeah, I've seen.
Let's wait for news, thanks!

**Comment by delvedor** [comment]
I followed the post that you had linked, and now all works correctly.
Thanks a lot!

**Comment by cavestri** [comment]
Great, thanks!
